server:
  #tomcat端口号
  port: 8081
spring:
  dubbo:
    application:
      name: service
        # dubbo服务发布者接口所在的包（非实现类）
    base-package: com.gjj.website.facaded.service
    registry:
    # zookeeper注册中心的地址
      address: 127.0.0.1
    # zookeeper注册中心的端口
      port: 2181
    protocol:
      name: dubbo
      serialization: hessian2
    provider:
      retries: 0
  datasource:
    data-username: root
    data-password: admin
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/website?serverTimezone=UTC
mybatis:
    mapper-locations: classpath:com/gjj/website/service/mapper/xml/*Mapper.xml
    typeAliasesPackage: com.gjj.website.facaded.model
    configuration:
      map-underscore-to-camel-case: true
      use-generated-keys: true
